In [1]:
import pandas as pd

gait_df = pd.read_csv('./datasets/gait_features_2.csv')

participants = gait_df['participant']
features_df = gait_df.drop(columns=['participant'])

features_df.describe().T

,count,mean,std,min,25%,50%,75%,max
l_mean_stride_time,152.0,1.173509,0.130922,0.946667,1.066667,1.140000,1.243333,1.573333
r_mean_stride_time,152.0,1.176031,0.135992,0.940000,1.080000,1.140000,1.243333,1.613333
total_mean_stride_time,152.0,1.175301,0.131941,0.960000,1.073000,1.144000,1.240000,1.568000
l_mean_stride_dist,152.0,1400.133140,156.448341,1018.948789,1299.005208,1398.389587,1486.201502,1879.577304
r_mean_stride_dist,152.0,1413.747790,149.816462,1070.896634,1316.573449,1424.600781,1498.970634,1925.379027
total_mean_stride_dist,152.0,1403.732863,148.001177,1101.507206,1302.114814,1404.788706,1483.108147,1910.111786
l_r_mean_step_times,152.0,0.601816,0.065522,0.466667,0.556667,0.600000,0.640000,0.800000
r_l_mean_step_times,152.0,0.578443,0.081448,0.440000,0.520000,0.560000,0.630000,0.810000
total_mean_step_times,152.0,0.591007,0.066480,0.480000,0.542143,0.576000,0.632000,0.786667
l_r_mean_step_dist,152.0,710.085574,79.079638,489.157589,656.457642,707.239895,759.578544,964.169659
r_l_mean_step_dist,152.0,674.549943,90.006044,471.592581,610.178935,673.310940,726.267109,961.209369
total_mean_step_distance,152.0,690.798321,77.257705,514.947385,637.152362,689.149307,733.227745,962.689514
l_r_mean_step_width,152.0,138.054683,83.399163,40.829947,99.678186,122.847777,148.905000,788.225474
r_l_mean_step_width,152.0,138.414498,80.837624,33.974180,99.962704,119.142407,157.135061,766.275550
total_mean_step_width,152.0,138.268990,81.058537,36.259436,103.198842,120.753267,152.199774,777.250512
l_mean_max_hip_angle_diff,152.0,27.233002,5.133044,16.728521,23.307694,26.800143,29.979669,39.993741
r_mean_max_hip_angle_diff,152.0,27.179127,4.488559,17.498564,24.037959,27.228877,29.892871,36.941140
total_mean_max_hip_angle_diff,152.0,27.226529,4.384377,18.517060,24.630733,26.632828,29.859998,38.516039
l_mean_max_knee_angle_diff,152.0,67.000244,6.094550,45.878611,64.299815,67.523195,70.860668,79.208011
r_mean_max_knee_angle_diff,152.0,67.475626,5.922360,49.347294,63.805099,67.533385,72.005419,78.899804
total_mean_max_knee_angle_diff,152.0,67.210973,4.821620,52.988749,64.677287,67.220752,70.473358,77.962278
l_mean_max_ankle_angle_diff,152.0,42.007960,9.554524,22.713661,34.798693,41.619165,48.668222,63.911591
r_mean_max_ankle_angle_diff,152.0,39.436288,9.787021,18.097304,31.781377,39.873197,45.424924,62.207938
total_mean_max_ankle_angle_diff,152.0,40.716939,8.923430,21.542897,33.735534,41.238938,46.598182,62.582657
l_r_mean_step_l_angle,152.0,27.926239,6.107098,15.486697,23.311142,27.548182,32.830538,44.383625
r_l_mean_step_l_angle,152.0,28.536425,7.288979,13.391205,24.115621,27.409861,32.800521,51.960801
total_mean_step_l_angle,152.0,28.195048,6.101198,16.397405,24.009210,27.438868,32.750848,46.836158
l_l_mean_humerus_angle,152.0,20.783878,7.507577,6.865133,16.375066,20.252794,23.845553,46.817590
l_r_mean_humerus_angle,152.0,6.964285,4.428991,0.585541,3.224396,6.113012,9.737003,19.786736
r_r_mean_humerus_angle,152.0,19.775881,7.101157,5.416661,14.820994,19.570370,23.628010,41.902926
r_l_mean_humerus_angle,152.0,6.454603,3.585980,0.587248,3.937512,5.828588,8.358861,19.302011
one_side_mean_humerus_angle,152.0,20.282198,6.795798,7.705855,16.581652,19.567216,23.209209,43.017502
counter_side_mean_humerus_angle,152.0,6.757325,3.188633,1.544388,4.406561,6.389384,8.574672,16.513196
l_mean_max_elbow_angle_diff,152.0,21.147036,9.195451,0.000047,15.024555,20.210744,25.746691,51.265061
r_mean_max_elbow_angle_diff,152.0,18.112198,10.389131,3.647535,10.685870,16.446502,23.094478,52.235023
total_mean_max_elbow_angle_diff,152.0,19.608080,8.772682,4.542519,13.246606,18.349236,23.954457,48.772919
l_r_mean_cog_diff_heights,152.0,46.245180,11.631583,24.957084,36.664210,45.430342,54.633472,74.914561
r_l_mean_cog_diff_heights,152.0,44.925053,11.664893,21.951635,35.110577,45.388884,53.005560,68.878549
total_mean_cog_diff_heights,152.0,45.553720,11.302508,24.832458,36.449714,45.099413,54.618742,69.885189
l_r_mean_lateral_pelvic_tilt_diff,152.0,8.420527,3.225250,2.767594,6.175168,7.519012,10.160128,18.529783
r_l_mean_lateral_pelvic_tilt_diff,152.0,7.674458,3.398729,2.560655,5.285337,6.963163,9.709215,18.981428
total_mean_lateral_pelvic_tilt_diff,152.0,8.038369,3.137782,2.785054,5.742733,7.215471,10.059085,17.082430
l_mean_pelvis_rotation,152.0,6.716850,3.718899,0.248449,3.867573,6.251614,8.972170,19.542261
r_mean_pelvis_rotation,152.0,5.963585,3.080444,0.724728,3.666590,5.572027,8.026911,13.322355
total_mean_pelvis_rotation,152.0,6.359984,2.276930,1.739143,4.441731,6.376083,7.664877,13.868092

In [2]:
a = [col_name for col_name in gait_df.columns if col_name != "participant"] 
a

['l_mean_stride_time',
 'r_mean_stride_time',
 'total_mean_stride_time',
 'l_mean_stride_dist',
 'r_mean_stride_dist',
 'total_mean_stride_dist',
 'l_r_mean_step_times',
 'r_l_mean_step_times',
 'total_mean_step_times',
 'l_r_mean_step_dist',
 'r_l_mean_step_dist',
 'total_mean_step_distance',
 'l_r_mean_step_width',
 'r_l_mean_step_width',
 'total_mean_step_width',
 'l_mean_max_hip_angle_diff',
 'r_mean_max_hip_angle_diff',
 'total_mean_max_hip_angle_diff',
 'l_mean_max_knee_angle_diff',
 'r_mean_max_knee_angle_diff',
 'total_mean_max_knee_angle_diff',
 'l_mean_max_ankle_angle_diff',
 'r_mean_max_ankle_angle_diff',
 'total_mean_max_ankle_angle_diff',
 'l_r_mean_step_l_angle',
 'r_l_mean_step_l_angle',
 'total_mean_step_l_angle',
 'l_l_mean_humerus_angle',
 'l_r_mean_humerus_angle',
 'r_r_mean_humerus_angle',
 'r_l_mean_humerus_angle',
 'one_side_mean_humerus_angle',
 'counter_side_mean_humerus_angle',
 'l_mean_max_elbow_angle_diff',
 'r_mean_max_elbow_angle_diff',
 'total_mean_max_elbow_angle_diff',
 'l_r_mean_cog_diff_heights',
 'r_l_mean_cog_diff_heights',
 'total_mean_cog_diff_heights',
 'l_r_mean_lateral_pelvic_tilt_diff',
 'r_l_mean_lateral_pelvic_tilt_diff',
 'total_mean_lateral_pelvic_tilt_diff',
 'l_mean_pelvis_rotation',
 'r_mean_pelvis_rotation',
 'total_mean_pelvis_rotation']

In [3]:
col_names_wo_asym = [col_name for col_name in features_df.columns if col_name.startswith('total_mean')] + ['one_side_mean_humerus_angle', 'counter_side_mean_humerus_angle']
col_names_wo_asym

['total_mean_stride_time',
 'total_mean_stride_dist',
 'total_mean_step_times',
 'total_mean_step_distance',
 'total_mean_step_width',
 'total_mean_max_hip_angle_diff',
 'total_mean_max_knee_angle_diff',
 'total_mean_max_ankle_angle_diff',
 'total_mean_step_l_angle',
 'total_mean_max_elbow_angle_diff',
 'total_mean_cog_diff_heights',
 'total_mean_lateral_pelvic_tilt_diff',
 'total_mean_pelvis_rotation',
 'one_side_mean_humerus_angle',
 'counter_side_mean_humerus_angle']

In [4]:
len(col_names_wo_asym)

15

In [5]:
features_df[col_names_wo_asym].describe().T

,count,mean,std,min,25%,50%,75%,max
total_mean_stride_time,152.0,1.175301,0.131941,0.960000,1.073000,1.144000,1.240000,1.568000
total_mean_stride_dist,152.0,1403.732863,148.001177,1101.507206,1302.114814,1404.788706,1483.108147,1910.111786
total_mean_step_times,152.0,0.591007,0.066480,0.480000,0.542143,0.576000,0.632000,0.786667
total_mean_step_distance,152.0,690.798321,77.257705,514.947385,637.152362,689.149307,733.227745,962.689514
total_mean_step_width,152.0,138.268990,81.058537,36.259436,103.198842,120.753267,152.199774,777.250512
total_mean_max_hip_angle_diff,152.0,27.226529,4.384377,18.517060,24.630733,26.632828,29.859998,38.516039
total_mean_max_knee_angle_diff,152.0,67.210973,4.821620,52.988749,64.677287,67.220752,70.473358,77.962278
total_mean_max_ankle_angle_diff,152.0,40.716939,8.923430,21.542897,33.735534,41.238938,46.598182,62.582657
total_mean_step_l_angle,152.0,28.195048,6.101198,16.397405,24.009210,27.438868,32.750848,46.836158
total_mean_max_elbow_angle_diff,152.0,19.608080,8.772682,4.542519,13.246606,18.349236,23.954457,48.772919
total_mean_cog_diff_heights,152.0,45.553720,11.302508,24.832458,36.449714,45.099413,54.618742,69.885189
total_mean_lateral_pelvic_tilt_diff,152.0,8.038369,3.137782,2.785054,5.742733,7.215471,10.059085,17.082430
total_mean_pelvis_rotation,152.0,6.359984,2.276930,1.739143,4.441731,6.376083,7.664877,13.868092
one_side_mean_humerus_angle,152.0,20.282198,6.795798,7.705855,16.581652,19.567216,23.209209,43.017502
counter_side_mean_humerus_angle,152.0,6.757325,3.188633,1.544388,4.406561,6.389384,8.574672,16.513196

In [6]:
col_names_angles = [col_name for col_name in features_df.columns if ("angle" in col_name or "tilt" in col_name or "rotation" in col_name)]
print(len(col_names_angles))
col_names_angles

27

['l_mean_max_hip_angle_diff',
 'r_mean_max_hip_angle_diff',
 'total_mean_max_hip_angle_diff',
 'l_mean_max_knee_angle_diff',
 'r_mean_max_knee_angle_diff',
 'total_mean_max_knee_angle_diff',
 'l_mean_max_ankle_angle_diff',
 'r_mean_max_ankle_angle_diff',
 'total_mean_max_ankle_angle_diff',
 'l_r_mean_step_l_angle',
 'r_l_mean_step_l_angle',
 'total_mean_step_l_angle',
 'l_l_mean_humerus_angle',
 'l_r_mean_humerus_angle',
 'r_r_mean_humerus_angle',
 'r_l_mean_humerus_angle',
 'one_side_mean_humerus_angle',
 'counter_side_mean_humerus_angle',
 'l_mean_max_elbow_angle_diff',
 'r_mean_max_elbow_angle_diff',
 'total_mean_max_elbow_angle_diff',
 'l_r_mean_lateral_pelvic_tilt_diff',
 'r_l_mean_lateral_pelvic_tilt_diff',
 'total_mean_lateral_pelvic_tilt_diff',
 'l_mean_pelvis_rotation',
 'r_mean_pelvis_rotation',
 'total_mean_pelvis_rotation']

In [7]:
col_names_angles_and_time = col_names_angles + [col_name for col_name in features_df.columns if ("time" in col_name)]
print(len(col_names_angles_and_time))
col_names_angles_and_time

33

['l_mean_max_hip_angle_diff',
 'r_mean_max_hip_angle_diff',
 'total_mean_max_hip_angle_diff',
 'l_mean_max_knee_angle_diff',
 'r_mean_max_knee_angle_diff',
 'total_mean_max_knee_angle_diff',
 'l_mean_max_ankle_angle_diff',
 'r_mean_max_ankle_angle_diff',
 'total_mean_max_ankle_angle_diff',
 'l_r_mean_step_l_angle',
 'r_l_mean_step_l_angle',
 'total_mean_step_l_angle',
 'l_l_mean_humerus_angle',
 'l_r_mean_humerus_angle',
 'r_r_mean_humerus_angle',
 'r_l_mean_humerus_angle',
 'one_side_mean_humerus_angle',
 'counter_side_mean_humerus_angle',
 'l_mean_max_elbow_angle_diff',
 'r_mean_max_elbow_angle_diff',
 'total_mean_max_elbow_angle_diff',
 'l_r_mean_lateral_pelvic_tilt_diff',
 'r_l_mean_lateral_pelvic_tilt_diff',
 'total_mean_lateral_pelvic_tilt_diff',
 'l_mean_pelvis_rotation',
 'r_mean_pelvis_rotation',
 'total_mean_pelvis_rotation',
 'l_mean_stride_time',
 'r_mean_stride_time',
 'total_mean_stride_time',
 'l_r_mean_step_times',
 'r_l_mean_step_times',
 'total_mean_step_times']

In [8]:
two_walks_ptcpts, one_walk_ptcpts = [], []


for ptcpt, count in participants.value_counts().to_dict().items():
    if count == 8:
        two_walks_ptcpts.append(ptcpt)
    else: 
        one_walk_ptcpts.append(ptcpt)

print(len(one_walk_ptcpts), one_walk_ptcpts)
print(len(two_walks_ptcpts), two_walks_ptcpts)

26 [1, 2, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 32]
6 [31, 30, 29, 28, 27, 26]

In [9]:
import random
import math

def split_into_random_sublists(ptcpts_lst, n):
    splits = [[] for _ in range(n)]
    for idx, ptcpt in enumerate(ptcpts_lst):
        splits[idx%n].append(ptcpt)
    return splits

In [10]:
split_into_random_sublists(one_walk_ptcpts, 5)

[[1, 22, 17, 12, 7, 32],
 [2, 21, 16, 11, 6],
 [25, 20, 15, 10, 5],
 [24, 19, 14, 9, 4],
 [23, 18, 13, 8, 3]]

In [11]:
# 5 5 5 5 6

import random

random.shuffle(one_walk_ptcpts)
print(one_walk_ptcpts)

test_split = [one_walk_ptcpts[5*i:5*i+5] for i in range(4)] + [one_walk_ptcpts[-6:]]
test_split

[3, 32, 5, 22, 1, 2, 19, 7, 11, 24, 16, 25, 23, 12, 15, 13, 17, 14, 20, 4, 8, 6, 18, 21, 10, 9]

[[3, 32, 5, 22, 1],
 [2, 19, 7, 11, 24],
 [16, 25, 23, 12, 15],
 [13, 17, 14, 20, 4],
 [8, 6, 18, 21, 10, 9]]

In [2]:
import pandas as pd
from utils.cross_validation_siamese import CVTrainer

gait_df = pd.read_csv('./datasets/gait_features.csv')
cv_trainer = CVTrainer(gait_df)
cv_trainer.run_training()

2025-11-17 00:14:03,436 - logger - INFO - Provided selected_features parameter is None - all features from dataset will be used.
2025-11-17 00:14:03,437 - logger - INFO - Number of selected features: 24
2025-11-17 00:14:03,442 - logger - INFO - Found 26 participants recorded once.
2025-11-17 00:14:03,443 - logger - DEBUG - Participants recorded once: [1, 2, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 32]
2025-11-17 00:14:03,444 - logger - INFO - Found 6 participants recorded twice.
2025-11-17 00:14:03,444 - logger - DEBUG - Participants recorded twice: [31, 30, 29, 28, 27, 26]
2025-11-17 00:14:03,445 - logger - INFO - Training iteration 0/5
2025-11-17 00:14:03,616 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:03,617 - logger - INFO - Train dataset size: 576
2025-11-17 00:14:03,618 - logger - INFO - Test dataset size: 72
2025-11-17 00:14:03,619 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:03,792 - logger - INFO - Epoch 1, Train Loss: 0.1633
2025-11-17 00:14:03,970 - logger - INFO - Epoch 2, Train Loss: 0.1163
2025-11-17 00:14:04,202 - logger - INFO - Epoch 3, Train Loss: 0.0964
2025-11-17 00:14:04,380 - logger - INFO - Epoch 4, Train Loss: 0.0800
2025-11-17 00:14:04,562 - logger - INFO - Epoch 5, Train Loss: 0.0752
2025-11-17 00:14:04,763 - logger - INFO - Epoch 6, Train Loss: 0.0663
2025-11-17 00:14:04,939 - logger - INFO - Epoch 7, Train Loss: 0.0580
2025-11-17 00:14:05,126 - logger - INFO - Epoch 8, Train Loss: 0.0528
2025-11-17 00:14:05,324 - logger - INFO - Epoch 9, Train Loss: 0.0558
2025-11-17 00:14:05,521 - logger - INFO - Epoch 10, Train Loss: 0.0582
2025-11-17 00:14:05,522 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:05,546 - logger - INFO - Iteration results:
2025-11-17 00:14:05,549 - logger - INFO - Confusion matrix:
        True  False
True     28      8
False    11     25
2025-11-17 00:14:05,559 - logger - INFO - Accuracy: 0.736
2025-11-17 00:14:05,563 - logger - INFO - Precision: 0.718
2025-11-17 00:14:05,565 - logger - INFO - Recall: 0.778
2025-11-17 00:14:05,566 - logger - INFO - Training iteration 1/5
2025-11-17 00:14:05,755 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:05,756 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:05,757 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:05,758 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:05,939 - logger - INFO - Epoch 1, Train Loss: 0.1654
2025-11-17 00:14:06,162 - logger - INFO - Epoch 2, Train Loss: 0.1163
2025-11-17 00:14:06,383 - logger - INFO - Epoch 3, Train Loss: 0.1022
2025-11-17 00:14:06,575 - logger - INFO - Epoch 4, Train Loss: 0.0881
2025-11-17 00:14:06,756 - logger - INFO - Epoch 5, Train Loss: 0.0773
2025-11-17 00:14:06,945 - logger - INFO - Epoch 6, Train Loss: 0.0704
2025-11-17 00:14:07,124 - logger - INFO - Epoch 7, Train Loss: 0.0660
2025-11-17 00:14:07,318 - logger - INFO - Epoch 8, Train Loss: 0.0617
2025-11-17 00:14:07,502 - logger - INFO - Epoch 9, Train Loss: 0.0573
2025-11-17 00:14:07,692 - logger - INFO - Epoch 10, Train Loss: 0.0532
2025-11-17 00:14:07,693 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:07,708 - logger - INFO - Iteration results:
2025-11-17 00:14:07,711 - logger - INFO - Confusion matrix:
        True  False
True     21      9
False     0     30
2025-11-17 00:14:07,719 - logger - INFO - Accuracy: 0.850
2025-11-17 00:14:07,720 - logger - INFO - Precision: 1.000
2025-11-17 00:14:07,721 - logger - INFO - Recall: 0.700
2025-11-17 00:14:07,721 - logger - INFO - Training iteration 2/5
2025-11-17 00:14:07,889 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:07,890 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:07,891 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:07,892 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:08,071 - logger - INFO - Epoch 1, Train Loss: 0.1812
2025-11-17 00:14:08,272 - logger - INFO - Epoch 2, Train Loss: 0.1175
2025-11-17 00:14:08,480 - logger - INFO - Epoch 3, Train Loss: 0.0950
2025-11-17 00:14:08,667 - logger - INFO - Epoch 4, Train Loss: 0.0787
2025-11-17 00:14:08,854 - logger - INFO - Epoch 5, Train Loss: 0.0706
2025-11-17 00:14:09,045 - logger - INFO - Epoch 6, Train Loss: 0.0646
2025-11-17 00:14:09,226 - logger - INFO - Epoch 7, Train Loss: 0.0626
2025-11-17 00:14:09,411 - logger - INFO - Epoch 8, Train Loss: 0.0560
2025-11-17 00:14:09,592 - logger - INFO - Epoch 9, Train Loss: 0.0526
2025-11-17 00:14:09,767 - logger - INFO - Epoch 10, Train Loss: 0.0523
2025-11-17 00:14:09,767 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:09,784 - logger - INFO - Iteration results:
2025-11-17 00:14:09,787 - logger - INFO - Confusion matrix:
        True  False
True     25      5
False     6     24
2025-11-17 00:14:09,795 - logger - INFO - Accuracy: 0.817
2025-11-17 00:14:09,795 - logger - INFO - Precision: 0.806
2025-11-17 00:14:09,796 - logger - INFO - Recall: 0.833
2025-11-17 00:14:09,797 - logger - INFO - Training iteration 3/5
2025-11-17 00:14:10,000 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:10,001 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:10,002 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:10,004 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:10,186 - logger - INFO - Epoch 1, Train Loss: 0.1838
2025-11-17 00:14:10,380 - logger - INFO - Epoch 2, Train Loss: 0.1277
2025-11-17 00:14:10,553 - logger - INFO - Epoch 3, Train Loss: 0.1049
2025-11-17 00:14:10,745 - logger - INFO - Epoch 4, Train Loss: 0.0846
2025-11-17 00:14:10,939 - logger - INFO - Epoch 5, Train Loss: 0.0777
2025-11-17 00:14:11,162 - logger - INFO - Epoch 6, Train Loss: 0.0694
2025-11-17 00:14:11,359 - logger - INFO - Epoch 7, Train Loss: 0.0677
2025-11-17 00:14:11,560 - logger - INFO - Epoch 8, Train Loss: 0.0594
2025-11-17 00:14:11,746 - logger - INFO - Epoch 9, Train Loss: 0.0579
2025-11-17 00:14:11,919 - logger - INFO - Epoch 10, Train Loss: 0.0559
2025-11-17 00:14:11,920 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:11,934 - logger - INFO - Iteration results:
2025-11-17 00:14:11,937 - logger - INFO - Confusion matrix:
        True  False
True     21      9
False     2     28
2025-11-17 00:14:11,946 - logger - INFO - Accuracy: 0.817
2025-11-17 00:14:11,947 - logger - INFO - Precision: 0.913
2025-11-17 00:14:11,948 - logger - INFO - Recall: 0.700
2025-11-17 00:14:11,949 - logger - INFO - Training iteration 4/5
2025-11-17 00:14:12,132 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:12,134 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:12,134 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:12,136 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:12,309 - logger - INFO - Epoch 1, Train Loss: 0.1925
2025-11-17 00:14:12,496 - logger - INFO - Epoch 2, Train Loss: 0.1222
2025-11-17 00:14:12,680 - logger - INFO - Epoch 3, Train Loss: 0.1003
2025-11-17 00:14:12,859 - logger - INFO - Epoch 4, Train Loss: 0.0867
2025-11-17 00:14:13,041 - logger - INFO - Epoch 5, Train Loss: 0.0772
2025-11-17 00:14:13,228 - logger - INFO - Epoch 6, Train Loss: 0.0690
2025-11-17 00:14:13,399 - logger - INFO - Epoch 7, Train Loss: 0.0662
2025-11-17 00:14:13,688 - logger - INFO - Epoch 8, Train Loss: 0.0600
2025-11-17 00:14:13,882 - logger - INFO - Epoch 9, Train Loss: 0.0555
2025-11-17 00:14:14,068 - logger - INFO - Epoch 10, Train Loss: 0.0531
2025-11-17 00:14:14,069 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:14,084 - logger - INFO - Iteration results:
2025-11-17 00:14:14,088 - logger - INFO - Confusion matrix:
        True  False
True     26      4
False     1     29
2025-11-17 00:14:14,096 - logger - INFO - Accuracy: 0.917
2025-11-17 00:14:14,097 - logger - INFO - Precision: 0.963
2025-11-17 00:14:14,098 - logger - INFO - Recall: 0.867
2025-11-17 00:14:14,098 - logger - INFO - Training loop for all folds finished.
2025-11-17 00:14:14,099 - logger - INFO - Final results:
2025-11-17 00:14:14,102 - logger - INFO - Confusion matrix:
        True  False
True    121     35
False    20    136
2025-11-17 00:14:14,111 - logger - INFO - Accuracy: 0.824
2025-11-17 00:14:14,113 - logger - INFO - Precision: 0.858
2025-11-17 00:14:14,113 - logger - INFO - Recall: 0.776

In [3]:
gait_df = pd.read_csv('./datasets/gait_features_2.csv')
cv_trainer = CVTrainer(gait_df)
cv_trainer.run_training()

2025-11-17 00:14:16,485 - logger - INFO - Provided selected_features parameter is None - all features from dataset will be used.
2025-11-17 00:14:16,487 - logger - INFO - Number of selected features: 45
2025-11-17 00:14:16,492 - logger - INFO - Found 26 participants recorded once.
2025-11-17 00:14:16,493 - logger - DEBUG - Participants recorded once: [1, 2, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 32]
2025-11-17 00:14:16,493 - logger - INFO - Found 6 participants recorded twice.
2025-11-17 00:14:16,494 - logger - DEBUG - Participants recorded twice: [31, 30, 29, 28, 27, 26]
2025-11-17 00:14:16,494 - logger - INFO - Training iteration 0/5
2025-11-17 00:14:16,668 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:16,669 - logger - INFO - Train dataset size: 576
2025-11-17 00:14:16,669 - logger - INFO - Test dataset size: 72
2025-11-17 00:14:16,671 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:16,842 - logger - INFO - Epoch 1, Train Loss: 0.1382
2025-11-17 00:14:17,033 - logger - INFO - Epoch 2, Train Loss: 0.0821
2025-11-17 00:14:17,218 - logger - INFO - Epoch 3, Train Loss: 0.0609
2025-11-17 00:14:17,408 - logger - INFO - Epoch 4, Train Loss: 0.0467
2025-11-17 00:14:17,588 - logger - INFO - Epoch 5, Train Loss: 0.0398
2025-11-17 00:14:17,775 - logger - INFO - Epoch 6, Train Loss: 0.0343
2025-11-17 00:14:17,961 - logger - INFO - Epoch 7, Train Loss: 0.0289
2025-11-17 00:14:18,147 - logger - INFO - Epoch 8, Train Loss: 0.0247
2025-11-17 00:14:18,322 - logger - INFO - Epoch 9, Train Loss: 0.0221
2025-11-17 00:14:18,510 - logger - INFO - Epoch 10, Train Loss: 0.0204
2025-11-17 00:14:18,511 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:18,526 - logger - INFO - Iteration results:
2025-11-17 00:14:18,528 - logger - INFO - Confusion matrix:
        True  False
True     33      3
False     0     36
2025-11-17 00:14:18,537 - logger - INFO - Accuracy: 0.958
2025-11-17 00:14:18,538 - logger - INFO - Precision: 1.000
2025-11-17 00:14:18,539 - logger - INFO - Recall: 0.917
2025-11-17 00:14:18,540 - logger - INFO - Training iteration 1/5
2025-11-17 00:14:18,735 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:18,736 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:18,737 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:18,738 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:18,926 - logger - INFO - Epoch 1, Train Loss: 0.1519
2025-11-17 00:14:19,130 - logger - INFO - Epoch 2, Train Loss: 0.0936
2025-11-17 00:14:19,326 - logger - INFO - Epoch 3, Train Loss: 0.0674
2025-11-17 00:14:19,526 - logger - INFO - Epoch 4, Train Loss: 0.0494
2025-11-17 00:14:19,726 - logger - INFO - Epoch 5, Train Loss: 0.0457
2025-11-17 00:14:19,924 - logger - INFO - Epoch 6, Train Loss: 0.0389
2025-11-17 00:14:20,123 - logger - INFO - Epoch 7, Train Loss: 0.0343
2025-11-17 00:14:20,303 - logger - INFO - Epoch 8, Train Loss: 0.0324
2025-11-17 00:14:20,484 - logger - INFO - Epoch 9, Train Loss: 0.0264
2025-11-17 00:14:20,660 - logger - INFO - Epoch 10, Train Loss: 0.0250
2025-11-17 00:14:20,661 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:20,674 - logger - INFO - Iteration results:
2025-11-17 00:14:20,678 - logger - INFO - Confusion matrix:
        True  False
True     29      1
False     0     30
2025-11-17 00:14:20,686 - logger - INFO - Accuracy: 0.983
2025-11-17 00:14:20,687 - logger - INFO - Precision: 1.000
2025-11-17 00:14:20,688 - logger - INFO - Recall: 0.967
2025-11-17 00:14:20,688 - logger - INFO - Training iteration 2/5
2025-11-17 00:14:20,869 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:20,871 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:20,871 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:20,873 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:21,055 - logger - INFO - Epoch 1, Train Loss: 0.1310
2025-11-17 00:14:21,241 - logger - INFO - Epoch 2, Train Loss: 0.0751
2025-11-17 00:14:21,419 - logger - INFO - Epoch 3, Train Loss: 0.0587
2025-11-17 00:14:21,602 - logger - INFO - Epoch 4, Train Loss: 0.0462
2025-11-17 00:14:21,780 - logger - INFO - Epoch 5, Train Loss: 0.0376
2025-11-17 00:14:21,962 - logger - INFO - Epoch 6, Train Loss: 0.0364
2025-11-17 00:14:22,145 - logger - INFO - Epoch 7, Train Loss: 0.0268
2025-11-17 00:14:22,345 - logger - INFO - Epoch 8, Train Loss: 0.0272
2025-11-17 00:14:22,542 - logger - INFO - Epoch 9, Train Loss: 0.0261
2025-11-17 00:14:22,729 - logger - INFO - Epoch 10, Train Loss: 0.0209
2025-11-17 00:14:22,731 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:22,745 - logger - INFO - Iteration results:
2025-11-17 00:14:22,749 - logger - INFO - Confusion matrix:
        True  False
True     25      5
False     6     24
2025-11-17 00:14:22,763 - logger - INFO - Accuracy: 0.817
2025-11-17 00:14:22,774 - logger - INFO - Precision: 0.806
2025-11-17 00:14:22,776 - logger - INFO - Recall: 0.833
2025-11-17 00:14:22,776 - logger - INFO - Training iteration 3/5
2025-11-17 00:14:22,960 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:22,961 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:22,962 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:22,963 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:23,143 - logger - INFO - Epoch 1, Train Loss: 0.1733
2025-11-17 00:14:23,336 - logger - INFO - Epoch 2, Train Loss: 0.1003
2025-11-17 00:14:23,528 - logger - INFO - Epoch 3, Train Loss: 0.0750
2025-11-17 00:14:23,712 - logger - INFO - Epoch 4, Train Loss: 0.0560
2025-11-17 00:14:23,887 - logger - INFO - Epoch 5, Train Loss: 0.0475
2025-11-17 00:14:24,074 - logger - INFO - Epoch 6, Train Loss: 0.0378
2025-11-17 00:14:24,249 - logger - INFO - Epoch 7, Train Loss: 0.0384
2025-11-17 00:14:24,429 - logger - INFO - Epoch 8, Train Loss: 0.0337
2025-11-17 00:14:24,623 - logger - INFO - Epoch 9, Train Loss: 0.0283
2025-11-17 00:14:24,824 - logger - INFO - Epoch 10, Train Loss: 0.0253
2025-11-17 00:14:24,825 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:24,837 - logger - INFO - Iteration results:
2025-11-17 00:14:24,840 - logger - INFO - Confusion matrix:
        True  False
True     25      5
False     1     29
2025-11-17 00:14:24,849 - logger - INFO - Accuracy: 0.900
2025-11-17 00:14:24,850 - logger - INFO - Precision: 0.962
2025-11-17 00:14:24,851 - logger - INFO - Recall: 0.833
2025-11-17 00:14:24,852 - logger - INFO - Training iteration 4/5
2025-11-17 00:14:25,034 - logger - INFO - Train and test datasets created successfully
2025-11-17 00:14:25,036 - logger - INFO - Train dataset size: 588
2025-11-17 00:14:25,036 - logger - INFO - Test dataset size: 60
2025-11-17 00:14:25,037 - logger - INFO - Siamese neural network model training started...
2025-11-17 00:14:25,219 - logger - INFO - Epoch 1, Train Loss: 0.1295
2025-11-17 00:14:25,402 - logger - INFO - Epoch 2, Train Loss: 0.0801
2025-11-17 00:14:25,594 - logger - INFO - Epoch 3, Train Loss: 0.0555
2025-11-17 00:14:25,778 - logger - INFO - Epoch 4, Train Loss: 0.0457
2025-11-17 00:14:25,959 - logger - INFO - Epoch 5, Train Loss: 0.0403
2025-11-17 00:14:26,153 - logger - INFO - Epoch 6, Train Loss: 0.0339
2025-11-17 00:14:26,336 - logger - INFO - Epoch 7, Train Loss: 0.0293
2025-11-17 00:14:26,525 - logger - INFO - Epoch 8, Train Loss: 0.0267
2025-11-17 00:14:26,703 - logger - INFO - Epoch 9, Train Loss: 0.0251
2025-11-17 00:14:26,902 - logger - INFO - Epoch 10, Train Loss: 0.0231
2025-11-17 00:14:26,903 - logger - INFO - Siamese neural network model training finished
2025-11-17 00:14:26,917 - logger - INFO - Iteration results:
2025-11-17 00:14:26,920 - logger - INFO - Confusion matrix:
        True  False
True     28      2
False     3     27
2025-11-17 00:14:26,929 - logger - INFO - Accuracy: 0.917
2025-11-17 00:14:26,931 - logger - INFO - Precision: 0.903
2025-11-17 00:14:26,932 - logger - INFO - Recall: 0.933
2025-11-17 00:14:26,933 - logger - INFO - Training loop for all folds finished.
2025-11-17 00:14:26,933 - logger - INFO - Final results:
2025-11-17 00:14:26,936 - logger - INFO - Confusion matrix:
        True  False
True    140     16
False    10    146
2025-11-17 00:14:26,944 - logger - INFO - Accuracy: 0.917
2025-11-17 00:14:26,945 - logger - INFO - Precision: 0.933
2025-11-17 00:14:26,946 - logger - INFO - Recall: 0.897